//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 09:22:55 AM CDT 
//


package com.think.sparrowadmin.remexplus.config.v1_20;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for jobGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jobGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pomPath" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}filePathType"/>
 *         &lt;element name="testRunsPath" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}filePathType" minOccurs="0"/>
 *         &lt;element name="job" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}jobType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}identifierType" />
 *       &lt;attribute name="failAndContinue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="submitToAll" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="priority" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}jobPriorityType" default="0" />
 *       &lt;attribute name="groupId" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}identifierType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jobGroupType", propOrder = {
    "pomPath",
    "testRunsPath",
    "job"
})
public class JobGroupType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pomPath;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String testRunsPath;
    @XmlElement(required = true)
    protected List<JobType> job;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "failAndContinue")
    protected Boolean failAndContinue;
    @XmlAttribute(name = "submitToAll")
    protected Boolean submitToAll;
    @XmlAttribute(name = "priority")
    protected Integer priority;
    @XmlAttribute(name = "groupId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String groupId;

    /**
     * Gets the value of the pomPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPomPath() {
        return pomPath;
    }

    /**
     * Sets the value of the pomPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPomPath(String value) {
        this.pomPath = value;
    }

    /**
     * Gets the value of the testRunsPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestRunsPath() {
        return testRunsPath;
    }

    /**
     * Sets the value of the testRunsPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestRunsPath(String value) {
        this.testRunsPath = value;
    }

    /**
     * Gets the value of the job property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the job property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJob().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobType }
     * 
     * 
     */
    public List<JobType> getJob() {
        if (job == null) {
            job = new ArrayList<JobType>();
        }
        return this.job;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the failAndContinue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFailAndContinue() {
        if (failAndContinue == null) {
            return false;
        } else {
            return failAndContinue;
        }
    }

    /**
     * Sets the value of the failAndContinue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailAndContinue(Boolean value) {
        this.failAndContinue = value;
    }

    /**
     * Gets the value of the submitToAll property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSubmitToAll() {
        if (submitToAll == null) {
            return false;
        } else {
            return submitToAll;
        }
    }

    /**
     * Sets the value of the submitToAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubmitToAll(Boolean value) {
        this.submitToAll = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPriority() {
        if (priority == null) {
            return  0;
        } else {
            return priority;
        }
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

}
