//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 09:22:55 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dell.com/storage/test/remex/submit/config/v1_20")
package com.think.sparrowadmin.remexplus.config.v1_20;
