//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 09:22:55 AM CDT 
//


package com.think.sparrowadmin.remexplus.config.v1_20;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="poolGroups" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}poolGroupsType"/>
 *         &lt;element name="jobGroups" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}jobGroupsType"/>
 *         &lt;element name="submitGroups" type="{http://www.dell.com/storage/test/remex/submit/config/v1_20}submitGroupsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "poolGroups",
    "jobGroups",
    "submitGroups"
})
@XmlRootElement(name = "remexSubmit")
public class RemexSubmit {

    @XmlElement(required = true)
    protected PoolGroupsType poolGroups;
    @XmlElement(required = true)
    protected JobGroupsType jobGroups;
    @XmlElement(required = true)
    protected SubmitGroupsType submitGroups;

    /**
     * Gets the value of the poolGroups property.
     * 
     * @return
     *     possible object is
     *     {@link PoolGroupsType }
     *     
     */
    public PoolGroupsType getPoolGroups() {
        return poolGroups;
    }

    /**
     * Sets the value of the poolGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoolGroupsType }
     *     
     */
    public void setPoolGroups(PoolGroupsType value) {
        this.poolGroups = value;
    }

    /**
     * Gets the value of the jobGroups property.
     * 
     * @return
     *     possible object is
     *     {@link JobGroupsType }
     *     
     */
    public JobGroupsType getJobGroups() {
        return jobGroups;
    }

    /**
     * Sets the value of the jobGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobGroupsType }
     *     
     */
    public void setJobGroups(JobGroupsType value) {
        this.jobGroups = value;
    }

    /**
     * Gets the value of the submitGroups property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitGroupsType }
     *     
     */
    public SubmitGroupsType getSubmitGroups() {
        return submitGroups;
    }

    /**
     * Sets the value of the submitGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitGroupsType }
     *     
     */
    public void setSubmitGroups(SubmitGroupsType value) {
        this.submitGroups = value;
    }

}
