//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 03:10:08 PM CST 
//


package com.think.sparrowadmin.remexplus.config.v1_10;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dell.storage.test.remex.submit.config.v1_10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dell.storage.test.remex.submit.config.v1_10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RemexSubmit }
     * 
     */
    public RemexSubmit createRemexSubmit() {
        return new RemexSubmit();
    }

    /**
     * Create an instance of {@link PoolGroupsType }
     * 
     */
    public PoolGroupsType createPoolGroupsType() {
        return new PoolGroupsType();
    }

    /**
     * Create an instance of {@link JobGroupsType }
     * 
     */
    public JobGroupsType createJobGroupsType() {
        return new JobGroupsType();
    }

    /**
     * Create an instance of {@link SubmitGroupsType }
     * 
     */
    public SubmitGroupsType createSubmitGroupsType() {
        return new SubmitGroupsType();
    }

    /**
     * Create an instance of {@link PoolGroupType }
     * 
     */
    public PoolGroupType createPoolGroupType() {
        return new PoolGroupType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link PoolType }
     * 
     */
    public PoolType createPoolType() {
        return new PoolType();
    }

    /**
     * Create an instance of {@link SubmitGroupType }
     * 
     */
    public SubmitGroupType createSubmitGroupType() {
        return new SubmitGroupType();
    }

    /**
     * Create an instance of {@link JobGroupType }
     * 
     */
    public JobGroupType createJobGroupType() {
        return new JobGroupType();
    }

}
