//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 03:10:08 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dell.com/storage/test/remex/submit/config/v1_10")
package com.think.sparrowadmin.remexplus.config.v1_10;
